# Theme Settings
remote_theme: daattali/beautiful-jekyll@6.0.1

# Site Settings
title: "Tieu Hoang Huan Pham"
description: "PhD Student at University of Oklahoma specializing in machine learning applications in bioinformatics"
url: "https://huanpham5.github.io"
baseurl: "" # leave empty for user.github.io

# Author
author: "Tieu Hoang Huan Pham"
email: "pham0226@ou.edu"
avatar: "/assets/images/avatar.jpg" # place your photo in assets/images

# Personal Info
subtitle: "AI Researcher & Data Scientist"
bio: "PhD Student @ MoussaLab. Specializing in applying AI/ML to single cell genomics."
location: "Norman, OK"

# Navbar Links
navbar-links:
  About Me: "aboutme"
  Research: "research"
  Portfolio: "portfolio"
  Publications: "publications"
  CV: "assets/cv.pdf"
  Contact: "contact"

# Social Links
social-network-links:
  github: HuanPham5
  linkedin: tieu-hoang-huan-pham-627a71254
  email: pham0226@ou.edu
  # scholar: yourScholarID

# Footer (same as social)
footer-links:
  github: HuanPham5
  linkedin: tieu-hoang-huan-pham-627a71254
  email: pham0226@ou.edu

# Plugins (supported by GitHub Pages)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

# Pagination
paginate: 5

gtag:
  tracking_id: "G-XXXXXXXXXX"
