# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Tieu Hoang Huan Pham"
title_separator: "-"
subtitle: "AI Researcher & Data Scientist"
name: "Tieu Hoang Huan Pham"
description: "PhD Student at University of Oklahoma specializing in machine learning application in bioinformatics"
url: "https://huanpham5.github.io/"
baseurl: ""
repository: "HuanPham5/HuanPham5.github.io"

# Site Author
author:
  name: "Tieu Hoang Huan Pham"
  avatar: "/assets/images/avatar.jpg" # Add your photo
  bio: "PhD Student @ MoussaLab. Specializing in applying AI/ML to single cell genomics."
  location: "Norman, OK"
  email: "pham0226@ou.edu"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tieu-hoang-huan-pham-627a71254"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HuanPham5"
    # - label: "Google Scholar"
    #   icon: "fas fa-fw fa-graduation-cap"
    #   url: "#" # Add your Google Scholar link

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tieu-hoang-huan-pham-627a71254"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HuanPham5"

# Reading Files
include:
  - .htaccess
  - _pages

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Analytics (optional)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "YOUR-GA-ID"
    anonymize_ip: false